tar cvzf images_a.tar.gz images/{a,A}*/*
tar cvzf images_b.tar.gz images/{b,B}*/*
tar cvzf images_c.tar.gz images/{c,C}*/*
tar cvzf images_d.tar.gz images/{d,D}*/*
tar cvzf images_e.tar.gz images/{e,E}*/*
tar cvzf images_f.tar.gz images/{f,F}*/*
tar cvzf images_g.tar.gz images/{g,G}*/*
tar cvzf images_h.tar.gz images/{h,H}*/*
tar cvzf images_i.tar.gz images/{i,I}*/*
tar cvzf images_j.tar.gz images/{j,J}*/*
tar cvzf images_k.tar.gz images/{k,K}*/*
tar cvzf images_l.tar.gz images/{l,L}*/*
tar cvzf images_m.tar.gz images/{m,M}*/*
tar cvzf images_n.tar.gz images/{n,N}*/*
tar cvzf images_o.tar.gz images/{o,O}*/*
tar cvzf images_p.tar.gz images/{p,P}*/*
tar cvzf images_q.tar.gz images/{q,Q}*/*
tar cvzf images_r.tar.gz images/{r,R}*/*
tar cvzf images_s.tar.gz images/{s,S}*/*
tar cvzf images_t.tar.gz images/{t,T}*/*
tar cvzf images_u.tar.gz images/{u,U}*/*
tar cvzf images_v.tar.gz images/{v,V}*/*
tar cvzf images_w.tar.gz images/{w,W}*/*
tar cvzf images_x.tar.gz images/{x,X}*/*
tar cvzf images_y.tar.gz images/{y,Y}*/*
tar cvzf images_z.tar.gz images/{z,Z}*/*
